### ISSUE TITLE
receive port could be busy

### ISSUE THREAD

**Issue by henning-schild** [Innovailable/pypwrctrl#4]
The UDP protocol dictates that we need to be a server to listen for answers of the devices. That resource can be busy i.e. because we run multiple instances at the same time.

Reproduce with

```
--- a/pypwrctrl/pypwrctrl.py
+++ b/pypwrctrl/pypwrctrl.py
@@ -122,6 +122,7 @@ class PlugMaster:
                 self.sin.setsockopt(socket.SOL_SOCKET, socket.SO_BINDTODEVICE,
                                     bytes(iface, 'UTF-8'))
         self.sin.bind(('0.0.0.0', pin))
+        time.sleep(5)
 
         self.sout = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
         self.sout.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
```

to increase your chances ... And now run this twice `./main.py -d show`

You will get 

```
Traceback (most recent call last):
  File "./main.py", line 335, in <module>
    sys.exit(main())
  File "./main.py", line 322, in main
    master = PlugMaster(options.pin, options.pout, options.user,
  File "/home/henning/data/pypwrctrl/pypwrctrl/pypwrctrl.py", line 124, in __init__
    self.sin.bind(('0.0.0.0', pin))
OSError: [Errno 98] Address already in use
```

**Comment by henning-schild** [comment]
Seen in a test lab running automated on device tests and running that command pretty often

https://source.denx.de/Xenomai/xenomai-images/-/jobs/255469#L3126

@jan-kiszka

**Comment by henning-schild** [comment]
Solution could be to sit and wait while trying again a couple of times.

**Comment by thammi** [comment]
I personally would prefer to handle this error in the surrounding application, but I am willing to merge something like this with a reasonable timeout. Maybe there should be an option if the wait time has to be more than 1-2 seconds.

I created a pull request with alternative syntax and a bit faster retries. Could you please check whether it resolves your problem?

PS: I hope it's okay that I added my own implementation. It's just a bit easier to read to me.

**Comment by henning-schild** [comment]
Thanks. Your implementation looks better. Thanks for looking into it, handling it directly is better because the application is closer to the problem and actually causing it. I also thought about an outside solution, but why not go upstream and do something about it at the core.
